# Generated by Django 4.1.2 on 2022-10-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmatrixnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmatrixnumbers',
            name='form_data',
            field=models.CharField(default='some value', max_length=150),
        ),
        migrations.AddField(
            model_name='orgmatrixnumbers',
            name='not_clasified',
            field=models.CharField(default='some value', max_length=150),
        ),
    ]
