# Generated by Django 4.1.2 on 2022-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmatrixnumbers', '0002_orgmatrixnumbers_form_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmatrixnumbers',
            name='not_clasified',
            field=models.CharField(default=[3, 5, 5, 6, 8, 3, 4, 4, 7, 7, 1, 1, 2], max_length=150),
        ),
    ]
