# Generated by Django 4.1.2 on 2022-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmatrixnumbers', '0003_alter_orgmatrixnumbers_not_clasified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmatrixnumbers',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='orgmatrixnumbers',
            name='not_clasified',
        ),
        migrations.AddField(
            model_name='orgmatrixnumbers',
            name='clasificado',
            field=models.CharField(default='clasificado:[1, 2, 3, 4, 5, 6, 7, 8, 5, 3, 4, 7, 1]', max_length=150),
        ),
        migrations.AddField(
            model_name='orgmatrixnumbers',
            name='sin_clasificar',
            field=models.CharField(default='sin clasificar:[3, 5, 5, 6, 8, 3, 4, 4, 7, 7, 1, 1, 2]', max_length=150),
        ),
    ]
